# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr=np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9]).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [1]:
import numpy as np
arr1=np.arange(20).reshape(5,4)
arr2=np.arange(24).reshape(6,4)
print(f'Array 1:\n{arr1}')
print(f'Array 2:\n{arr2}')
print(f'After stacking:\n{np.vstack((arr2,arr1))}')

Array 1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Array 2:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
After stacking:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
arr1=np.arange(20).reshape(4,5)
arr2=np.arange(24).reshape(4,6)
print(f'Horizontal stack:\n{np.hstack((arr1,arr2))}')


Horizontal stack:
[[ 0  1  2  3  4  0  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10 11]
 [10 11 12 13 14 12 13 14 15 16 17]
 [15 16 17 18 19 18 19 20 21 22 23]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [10]:
arr=np.arange(15).reshape(3,5)
print(f'Array:\n{arr}')
print(f'Conversion:\n{np.ravel(arr)}')
print(f'Original array\n{arr}')

Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Conversion:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Original array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [15]:
###By applying np.ravel() or flatten() we can convert highier dimension into one dimension
arr1d=arr.flatten()
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [17]:
arr1d.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [6]:
arr=np.arange(25).reshape(5,5)
arr**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr=np.arange(30).reshape(5,6)
arr.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
arr.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [23]:
np.median(arr)

7.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
arr.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [20]:
arr=np.arange(16).reshape(4,4)
su=arr.diagonal()
print(f'Original array:\n{arr}')
print(f'Diagonal Matrix:\n{su}')
print(f'Sum of Diagonal:\n{arr.trace()}')

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal Matrix:
[ 0  5 10 15]
Sum of Diagonal:
30


## Question:13

### Find the determinant of the previous array in Q12?

In [21]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [7]:
arr=np.arange(15).reshape(3,5)
print(f'5th percentile\n{np.percentile(arr,5)}')
print(f'95th percentile\n{np.percentile(arr,95)}')


5th percentile
0.7000000000000001


## Question:15

### How to find if a given array has any null values?

In [22]:
np.any(arr)==0

False