# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
import numpy as np
a=np.zeros((10),dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a vector with values ranging from 10 to 49

In [5]:
import numpy as np
vector=np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [6]:
vector.shape

(39,)

5. Print the type of the previous array in question 3

In [9]:
vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [14]:
import numpy as np
print(np.__version__)

1.19.4


7. Print the dimension of the array in question 3


In [15]:
vector.ndim

1

8. Create a boolean array with all the True values

In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6],dtype=bool)
a

array([ True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [26]:
import numpy as np
aray=np.array([(2,3),[2,9]])
aray

array([[2, 3],
       [2, 9]])

10. Create a three dimensional array



In [30]:
import numpy as np
a=np.arange(64).reshape(2,8,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [2]:
import numpy as np
a=np.arange(15)
a[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [42]:
a=np.zeros((10))
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [45]:
arr=np.array([1,2,3,4,5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [11]:
arr1=np.array([[1,2,3],[4,5,6]],dtype=float)
arr2=np.array([[0,4,1],[7,2,12]],dtype=float)
a=arr1*arr2 
a

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [13]:
compare=arr1==arr2
compare

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [3]:
arr=np.arange(10)
a=arr[1:9:2]
a

array([1, 3, 5, 7])

18. Replace all odd numbers to -1 from previous array

In [11]:
a[::]=-1
a

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [12]:
arr = np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr2d=np.ones((5,5))
arr2d[1:-1,1:-1]=0
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [30]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [31]:
arr3d=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr3d[0:1]=64
arr3d

array([[64, 64, 64, 64, 64, 64],
       [ 7,  8,  9, 10, 11, 12]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [11]:
a=np.arange(9).reshape((3,3))
print("Original Array:")
print(a)
a[0]

Original Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [14]:
print("Original array:")
print(a)
a[1]


Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([3, 4, 5])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [17]:
print("Original array:")
print(a)
a[0:2,2:]

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [2]:
import numpy as np
rg=np.random.default_rng(100)
f=rg.random((10,10))
print("Original array:")
print(f)
minimum=f.min()
maximum=f.max()
print("Minimum number is:")
print(minimum)
print("Maximum number is: ")
print(maximum)


Original array:
[[0.83498163 0.59655403 0.28886324 0.04295157 0.9736544  0.5964717
  0.79026316 0.91033938 0.68815445 0.18999147]
 [0.98147898 0.28474005 0.62927317 0.58103648 0.59991227 0.53524811
  0.9957771  0.50194608 0.77102258 0.49416178]
 [0.99767449 0.97862192 0.39356804 0.32192526 0.86218065 0.7993249
  0.69143063 0.40851785 0.38976513 0.1316484 ]
 [0.62549749 0.08240137 0.27457299 0.65611703 0.01467603 0.83453217
  0.07239908 0.52412082 0.54655052 0.22724696]
 [0.95597822 0.34096385 0.50470744 0.86738361 0.65695295 0.38472241
  0.09627241 0.95580562 0.58956713 0.58216289]
 [0.59714527 0.14887393 0.56004863 0.56316752 0.58098818 0.184949
  0.70961891 0.07002066 0.32486494 0.10685547]
 [0.74802869 0.50157401 0.4663081  0.07369337 0.44209638 0.22351108
  0.30297573 0.39434801 0.70663065 0.78636314]
 [0.3568361  0.67012985 0.51022312 0.67114526 0.33033207 0.89841956
  0.66279201 0.19179735 0.57515853 0.74940288]
 [0.77992533 0.43773156 0.27831268 0.61602408 0.72990134 0.50723515


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [3]:
a=np.array([1,2.3,4,3,2,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
c

array([2., 4.])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [33]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_postion=np.intersect1d(a,b,return_indices=True)
common_postion

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [7]:
 names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
 data = np.random.randn(7, 4)
 data[~(names=='Will')]

array([[ 0.40484566, -0.24214236,  0.4994928 ,  0.0066763 ],
       [-0.51852015,  0.34097244,  0.06259806, -0.82874825],
       [-1.36329842, -1.44698096, -0.19252198,  2.34451441],
       [-0.84584946,  0.39061816, -0.06341397,  0.02677118],
       [ 0.76642648,  0.75049037,  0.62259633,  0.39634052]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [8]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
common=data[(names!='Will')&(names!='Joe')]
common

array([[ 1.34468395, -1.55560488,  0.40093139, -0.8460796 ],
       [-0.34885213, -1.79144326,  1.23879368,  0.54733002]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [55]:
import numpy as np
arr2d=np.arange(15).reshape((5,3))
print(f'Original array\n {arr2d}')
arr2d=arr2d.astype(np.float64)
print(f'Array in decimals:\n{arr2d} ')

Original array
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Array in decimals:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]] 


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [56]:
arr3d=np.arange(16).reshape(2,2,4)
print(f"Original array:\n{arr3d}")
arr3d=arr3d.astype(np.float64)
print(f'Required array is:\n{arr3d}')

Original array:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
Required array is:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]


33. Swap axes of the array you created in Question 32

In [58]:
print(f"Original array:\n{arr3d}")
swaping=np.swapaxes(arr3d,2,1)
print(f'After swapping\n{swaping}')

Original array:
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
After swapping
[[[ 0.  4.]
  [ 1.  5.]
  [ 2.  6.]
  [ 3.  7.]]

 [[ 8. 12.]
  [ 9. 13.]
  [10. 14.]
  [11. 15.]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [59]:
arr=np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [13]:
import numpy as np
arr1=np.random.randn(12)
arr2=np.random.randn(12)
print(f'Array # 1:\n {arr1}')
print(f'Array # 2:\n {arr2}')
print(f'Maximum elements btw those two: \n{np.maximum(arr1,arr2)}')

Array # 1:
 [ 0.29541336  0.29630094 -0.95518677  0.77414101  1.65620864  1.33757151
  0.63531444  0.86646267 -0.84790438  1.53577649  0.34085196  0.76459375]
Array # 2:
 [-0.17781723  0.67583372 -2.15866168 -0.2998569   0.01902753 -0.6566381
 -0.43926018  0.29221389 -1.82903043  1.32250255 -0.3112564   0.25051894]
Maximum elements btw those two: 
[ 0.29541336  0.67583372 -0.95518677  0.77414101  1.65620864  1.33757151
  0.63531444  0.86646267 -0.84790438  1.53577649  0.34085196  0.76459375]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names,return_index=True)

(array(['Bob', 'Joe', 'Will'], dtype='<U4'), array([0, 1, 2], dtype=int64))

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [6]:
import numpy as np
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [8]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
sampleArray[1]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [10]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=x.dot(y)
z


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [8]:
arr=np.random.randn(20)
print(f'Original\n{arr}')
sum=np.cumsum(arr)
print(f'Sum\n{sum}')
print("End")


Original
[-1.43698703 -0.06392979  1.44741252 -1.38023416 -1.48358714  1.03905709
 -1.83445481 -0.22892424 -1.07221845 -0.86732812 -0.00584843  0.55226047
 -0.24636769 -1.00281597  0.92315258 -0.82534609  0.34569862  0.96789143
 -0.53398344  0.11226588]
Sum
[-1.43698703 -1.50091682 -0.0535043  -1.43373846 -2.9173256  -1.87826851
 -3.71272332 -3.94164756 -5.01386602 -5.88119414 -5.88704257 -5.3347821
 -5.58114979 -6.58396576 -5.66081318 -6.48615927 -6.14046065 -5.17256922
 -5.70655267 -5.59428679]
